### ISSUE TITLE
Any plan to release for Magento 2?

### ISSUE THREAD

**Issue by elfeffe** [santerref/mag-products-integration#3]
it was int he plans, is there any advance?

**Comment by santerref** [comment]
The release date will be around the end of February or March. I will keep you in touch :)

**Comment by elfeffe** [comment]
Yeah, that will be great

**Comment by santerref** [comment]
@elfeffe 

Just to let you know that the new version is almost ready :)

**Comment by elfeffe** [comment]
Yeah!

**Comment by elfeffe** [comment]
@santerref Stopped because of COVID-19?

**Comment by elfeffe** [comment]
@santerref can you at leasat share what you have? I can collaborate too

**Comment by santerref** [comment]
Hello @elfeffe 

I am working again on the V2 of the plugin !

More details coming soon.

**Comment by santerref** [comment]
Hi @elfeffe 

It's a work in progress but you can download the branch `feature/magento-2` and try the most recent version! https://github.com/santerref/mag-products-integration/tree/feature/magento-2

Send me your feedback if you want :) 

santerref

**Comment by elfeffe** [comment]
Great! Thank you

**Comment by FiLeVeR10** [comment]
I've got a fork working with M2. https://github.com/FiLeVeR10/mag-products-integration

- I didn't have a multistore instance to be able to test the store value (currently disabled).
- Added the ability to have a theme template file for products display (At first I made changes to products.php, then just added the ability to control it in a theme template instead)
- Changed the store abstract to match the theme I was working with (would be great if this markup was in control outside of the plugin. Just super helpful to control the containers and attributes)
- Something about how it handled missing images was generating an error. I just commented out the lines causing issues, wasn't sure what the intent was to know how the issue should be addressed.

https://github.com/smartwebdev funded the updates. please give them and myself credit if you use any of the work I added.

**Comment by santerref** [comment]
Hi everyone, the first version for Magento 2 (2.0.0) is out !

@FiLeVeR10 @elfeffe 

https://wordpress.org/plugins/mag-products-integration/
